-- MySQL Script generated by MySQL Workbench
-- Sat Feb  6 22:21:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_SGSV
-- -----------------------------------------------------
-- DB_Sistema Gerenciador de Sessão de Votação

-- -----------------------------------------------------
-- Schema db_SGSV
--
-- DB_Sistema Gerenciador de Sessão de Votação
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_SGSV` DEFAULT CHARACTER SET utf8 ;
USE `db_SGSV` ;

-- -----------------------------------------------------
-- Table `db_SGSV`.`TB_SESSAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_SGSV`.`TB_SESSAO` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pauta` VARCHAR(255) NOT NULL,
  `dt_abertura` DATETIME NOT NULL,
  `qt_duracao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_SGSV`.`TB_ASSOCIADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_SGSV`.`TB_ASSOCIADO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_SGSV`.`TB_VOTACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_SGSV`.`TB_VOTACAO` (
  `associado_id` BIGINT NOT NULL,
  `sessao_id` BIGINT NOT NULL,
  `voto` CHAR(3) NOT NULL,
  PRIMARY KEY (`associado_id`, `sessao_id`),
  INDEX `FK_TB_VOTACAO_TB_SESSAO_IDX` (`sessao_id` ASC),
  INDEX `FK_TB_VOTACAO_TB_ASSOCIADO_IDX` (`associado_id` ASC),
  CONSTRAINT `FK_TB_VOTACAO_TB_ASSOCIADO`
    FOREIGN KEY (`associado_id`)
    REFERENCES `db_SGSV`.`TB_ASSOCIADO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TB_VOTACAO_TB_SESSAO`
    FOREIGN KEY (`sessao_id`)
    REFERENCES `db_SGSV`.`TB_SESSAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
