
    create table tb_associado (
       id bigint generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_sessao (
       id bigint generated by default as identity,
        dt_abertura timestamp,
        qt_duracao integer,
        pauta varchar(255),
        primary key (id)
    );

    create table tb_votacao (
       id bigint generated by default as identity,
        associado_id bigint,
        sessao_id bigint,
        primary key (id)
    );

    alter table tb_votacao 
       add constraint FKk5adayaqi6s7v0bb0cvsol01r 
       foreign key (associado_id) 
       references tb_associado;

    alter table tb_votacao 
       add constraint FKbsfk249hf3l4vs3r0xljml9s 
       foreign key (sessao_id) 
       references tb_sessao;
